name       : attr
version    : 2.4.47
release    : 11
source     :
    - http://download.savannah.gnu.org/releases/attr/attr-2.4.47.src.tar.gz : 25772f653ac5b2e3ceeb89df50e4688891e21f723c460636548971652af0a859
license    :
    - LGPL-3.0
autodep    : no
summary    : Extended attribute shared library
component  : system.base
description: |
    Contains the runtime environment required by programs that make use of extended attributes.
setup      : |
    # Help with musl builds
    export CFLAGS="${CFLAGS/-D_FORTIFY_SOURCE=2/}"
    %configure --bindir=/bin \
               --libexecdir=%libdir%
emul32     : yes
build      : |
    %make
install    : |
    %make_install install-lib install-dev DIST_ROOT=$installdir
    rm $installdir/%libdir%/*.la
    %make clean
