name        : attr
version     : 2.4.46
release     : 5
source      :
    - http://download.savannah.gnu.org/releases/attr/attr-2.4.46.src.tar.gz : dcd69bdca7ff166bc45141eddbcf21967999a6b66b0544be12a1cc2fd6340e1f
license     :
    - LGPL-3.0
autodep     : no
summary     : Extended attribute shared library
description : |
    Contains the runtime environment required by programs that make use of extended attributes.
setup      : |
    %configure --disable-static \
               --bindir=/bin \
               --libexecdir=%libdir%
build      : |
    %make
install    : |
    %make_install install-lib install-dev DIST_ROOT=$installdir
    rm $installdir/%libdir%/*.la
