name       : attr
version    : 2.4.48
release    : 13
source     :
    - https://download.savannah.gnu.org/releases/attr/attr-2.4.48.tar.gz : 5ead72b358ec709ed00bbf7a9eaef1654baad937c001c044fe8b74c57f5324e7
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : system.base
summary    : Extended attribute shared library
description: |
    Contains the runtime environment required by programs that make use of extended attributes.
autodep    : no
emul32     : yes
setup      : |
    %patch -p1 < $pkgfiles/Switch-back-to-syscall.patch

    # Help with musl builds
    export CFLAGS="${CFLAGS/-D_FORTIFY_SOURCE=2/}"
    %configure --bindir=/bin \
               --libexecdir=%libdir%
build      : |
    %make
install    : |
    %make_install
    rm $installdir/%libdir%/*.la
